services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-bank
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - "5432:5432"